/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import model.Item;
import model.Lesson;
import model.Payment;
import model.Student;
import model.Teacher;
import service.CourseService;

/**
 *
 * @author Asus
 */
public class NewPaymentFrame extends javax.swing.JFrame {

    private CourseService courseService;

    /**
     * Creates new form NewPaymentFrame
     */
    public NewPaymentFrame() {
        initComponents();
    }

    public NewPaymentFrame(CourseService courseService) {
        this.courseService = courseService;
        initComponents();
        showStudentCombo();
        showTeacherCombo();
        showLessonCombo();//Combo-larin icini doldurmaq ucundur.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        saveBtn = new javax.swing.JButton();
        studentCmb = new javax.swing.JComboBox<>();
        teacherCmb = new javax.swing.JComboBox<>();
        lessonCmb = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Student");

        jLabel2.setText("Teacher");

        jLabel3.setText("Lesson");

        jLabel4.setText("Amount");

        saveBtn.setText("Save");
        saveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveBtnActionPerformed(evt);
            }
        });

        studentCmb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Student" }));
        studentCmb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                studentCmbActionPerformed(evt);
            }
        });

        teacherCmb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Teacher", " " }));

        lessonCmb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Lesson" }));
        lessonCmb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lessonCmbActionPerformed(evt);
            }
        });

        jLabel5.setText("  AZN");

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(75, 75, 75)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(studentCmb, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(teacherCmb, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lessonCmb, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(46, 46, 46)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(118, 118, 118)
                        .addComponent(saveBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(173, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(studentCmb, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addComponent(teacherCmb, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(lessonCmb, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(135, 135, 135)
                .addComponent(saveBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(173, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void studentCmbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studentCmbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_studentCmbActionPerformed

    private void saveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBtnActionPerformed
        Item studentCmbVal = (Item) studentCmb.getSelectedItem();
        Item teacherCmbVal = (Item) teacherCmb.getSelectedItem();
        Item lessonCMbVal = (Item) lessonCmb.getSelectedItem();
        Payment payment = new Payment();
        Student student = new Student();
        student.setId(studentCmbVal.getId());
        Teacher teacher = new Teacher();
        teacher.setId(teacherCmbVal.getId());
        Lesson lesson = new Lesson();
        lesson.setId(lessonCMbVal.getId());
        payment.setStudent(student);
        payment.setTeacher(teacher);
        payment.setLesson(lesson);
        payment.setAmount(Double.parseDouble(jTextField1.getText()));
        try {
            boolean isAdded = courseService.addPayment(payment);
              if (isAdded) {
                JOptionPane.showMessageDialog(null, "Payment has been added successfully!");//null default olaraq yazilir eslinde freymin adi yazilir orda
            } else {
                JOptionPane.showMessageDialog(null, "Problem!Payment has not been added successfully !", "Error", JOptionPane.ERROR_MESSAGE);
            }
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_saveBtnActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void lessonCmbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lessonCmbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lessonCmbActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JComboBox<String> lessonCmb;
    private javax.swing.JButton saveBtn;
    private javax.swing.JComboBox<String> studentCmb;
    private javax.swing.JComboBox<String> teacherCmb;
    // End of variables declaration//GEN-END:variables

    private void showStudentCombo() {
        DefaultComboBoxModel studentCombo = (DefaultComboBoxModel) studentCmb.getModel();
        try {
            List<Student> studentList = courseService.getstudentList();
            for (Student student : studentList) {
                studentCombo.addElement(new Item(student.getId(), student.getName() + " " + student.getSurname()));
            }
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }

    private void showTeacherCombo() {
        DefaultComboBoxModel teacherCombo = (DefaultComboBoxModel) teacherCmb.getModel();
        try {
            List<Teacher> teacherList = courseService.getTeacherList();
            for (Teacher teacher : teacherList) {
                teacherCombo.addElement(new Item(teacher.getId(), teacher.getName() + " " + teacher.getSurname()));
            }
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }

    private void showLessonCombo() {
        DefaultComboBoxModel lessonCombo = (DefaultComboBoxModel) lessonCmb.getModel();
        try {
            List<Lesson> lessonList = courseService.getLessonList();
            for (Lesson lesson : lessonList) {
                lessonCombo.addElement(new Item(lesson.getId(), lesson.getLessonName()));
            }
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }
}
