/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import model.Item;
import model.Login;
import model.Role;
import model.Student;
import model.Teacher;
import service.CourseService;
import service.LoginService;
import util.Methods;

/**
 *
 * @author Asus
 */
public class NewRegistrationFrame extends javax.swing.JFrame {

    private CourseService courseService;
    private LoginService loginService;

    public NewRegistrationFrame() {
        initComponents();
    }

    public NewRegistrationFrame(CourseService courseService) {
        initComponents();
        this.courseService = courseService;
        showRoleCombo();
        changeEnabled(false);
    }

    NewRegistrationFrame(CourseService courseService, LoginService loginService) {
        initComponents();
        this.courseService = courseService;
        this.loginService = loginService;
        showRoleCombo();
        changeEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        registerBtn = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Role" }));
        jComboBox1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox1ItemStateChanged(evt);
            }
        });
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jLabel1.setText("Role");

        jLabel2.setText("People");

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select people" }));
        jComboBox2.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox2ItemStateChanged(evt);
            }
        });
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });

        jLabel3.setText("Email");

        registerBtn.setText("Register");
        registerBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerBtnActionPerformed(evt);
            }
        });

        jLabel5.setText("Name");

        jLabel6.setText("Surname");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addGap(82, 82, 82)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jComboBox2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField3)
                            .addComponent(jTextField2)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(133, 133, 133)
                        .addComponent(registerBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(48, 48, 48))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addComponent(registerBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(56, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed

    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jComboBox1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox1ItemStateChanged
        Item roleCombo = (Item) jComboBox1.getSelectedItem();
        try {
            if (roleCombo.getId() == 2) {
                changeEnabled(true);
                showStudentCombo();
                jComboBox2.setVisible(true);
                jLabel2.setVisible(true);
            } else if (roleCombo.getId() == 3) {
                changeEnabled(true);
                showTeacherCombo();
                jComboBox2.setVisible(true);
                jLabel2.setVisible(true);
            } else {
                changeEnabled(true);
                jComboBox2.setVisible(false);
                jLabel2.setVisible(false);
            }

        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jComboBox1ItemStateChanged

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void registerBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerBtnActionPerformed
        try {
            DateFormat df = new SimpleDateFormat("mmyyhhmss");
            Login login = new Login();
            String name = null;
            String surname = null;
            String username=jTextField1.getText();
            login.setUsername(username);
            String password = df.format(new java.util.Date());
            login.setPassword(Methods.geneRatePasswordToSha512(password, ""));
            Item item = (Item) jComboBox1.getSelectedItem();
            registerBtn.setVisible(false);
            if (item.getId() == 2 || item.getId() == 3) {
                //String people = (String) jComboBox2.getSelectedItem();
                name = jTextField2.getText();
                surname = jTextField3.getText();
            } else {
                name = jTextField2.getText();
                surname = jTextField3.getText();
            }
            Role role = new Role();
            role.setId(item.getId());
            login.setRole(role);
            login.setName(name);
            login.setSurname(surname);
            boolean isRegister = loginService.registration(login);
            boolean isSendMail=Methods.sendMail(username, "New password", "Your password is "+password);
            if (isRegister&& isSendMail) {
                JOptionPane.showMessageDialog(null, "Registration is succes!");
                this.dispose();
            } else {
                JOptionPane.showMessageDialog(null, "Problem!Registration is unsucces!", "Error", JOptionPane.ERROR_MESSAGE);

            }
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_registerBtnActionPerformed

    private void jComboBox2ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox2ItemStateChanged
        Item peopleCombo = (Item) jComboBox1.getSelectedItem();

        try {
            if (peopleCombo.getId() == 2) {
                Item studentCombo = (Item) jComboBox2.getSelectedItem();
                Student student = courseService.getStudentById(studentCombo.getId());
                jTextField1.setText(student.getEmail());
                jTextField2.setText(student.getName());
                jTextField3.setText(student.getSurname());
            } else if (peopleCombo.getId() == 3) {
                Item studentCombo = (Item) jComboBox2.getSelectedItem();
                Student student = courseService.getStudentById(studentCombo.getId());
                jTextField1.setText(student.getEmail());
                jTextField2.setText(student.getName());
                jTextField3.setText(student.getSurname());
            }
        } catch (Exception ex) {
            ex.printStackTrace();
        }


    }//GEN-LAST:event_jComboBox2ItemStateChanged

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JButton registerBtn;
    // End of variables declaration//GEN-END:variables

    private void showRoleCombo() {
        try {
            DefaultComboBoxModel roleCombo = (DefaultComboBoxModel) jComboBox1.getModel();
            List<Role> roleList = courseService.getRoleList();
            for (Role role : roleList) {
                roleCombo.addElement(new Item(role.getId(), role.getRoleName()));
            }
        } catch (Exception ex) {
            ex.printStackTrace();
        }

    }

    private void showStudentCombo() throws Exception {
        DefaultComboBoxModel peopleCombo = new DefaultComboBoxModel();
        jComboBox2.setModel(peopleCombo);
        List<Student> studentList = courseService.getstudentList();
        for (Student student : studentList) {
            peopleCombo.addElement(new Item(student.getId(), student.getName() + " " + student.getSurname()));
        }

    }

    private void showTeacherCombo() throws Exception {
        DefaultComboBoxModel peopleCombo = new DefaultComboBoxModel();
        jComboBox2.setModel(peopleCombo);
        List<Teacher> teacherList = courseService.getTeacherList();
        for (Teacher teacher : teacherList) {
            peopleCombo.addElement(new Item(teacher.getId(), teacher.getName() + " " + teacher.getSurname()));
        }

    }

    private void changeEnabled(boolean isChange) {
        jLabel5.setVisible(isChange);
        jLabel6.setVisible(isChange);
        jTextField2.setVisible(isChange);
        jTextField3.setVisible(isChange);

    }

}
